# devices:
# - "/dev/input/by-id/usb-*-event-kbd"

# startCommand: "ms qwerty"

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 400.0
mouseAccelerationCurve: 1.0

startMouseSpeed: 0.0

mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: qwerty
  bindings:
    f13: multi layer mouse ; exec ms mouse

- name: mouse
  passThrough: true
  bindings:
    esc: multi esc ; exec ms qwerty

    u: move -1 -1
    i: move  1 -1

    n: move -1  1
    m: move  1  1

    l: move  1  0
    h: move -1  0
    j: move  0  1
    k: move  0 -1

    w: move  2  0
    b: move -2  0

    f: button left
    d: button middle
    s: button right

    leftshift: toggle-layer mouse_shift
    rightshift: toggle-layer mouse_shift

    y: multi leftctrl+c ; layer qwerty
    c: leftctrl+leftshift+c
    v: leftctrl+leftshift+v

- name: mouse_shift
  passThrough: false
  bindings:
    j: scroll down
    k: scroll up

    w: move  4  0
    b: move -4  0

    a: speed 0.1
    s: speed 0.5
    d: speed 4
    f: speed 8
    g: speed 10
