devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# startCommand: "setxkbmap de"

mouseLoopInterval: 20

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0
mouseAccelerationCurve: 2.0
startMouseSpeed: 0.0
mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

quickTapTime: 150
comboTime: 200

layers:
- name: initial
  bindings:
    tab: tap-hold-next tab ; toggle-layer mouse ; 400

    a: tap-hold a ; leftalt ; 400
    s: tap-hold s ; toggle-layer system ; 400
    semicolon: tap-hold-next semicolon ; leftalt ; 400

    rightalt: toggle-layer arrows
    esc: tap-hold esc ; capslock ; 400
    capslock: tap-hold esc ; leftctrl ; 400
    apostrophe: tap-hold apostrophe ; rightctrl ; 400

    f+d: layer mouse

- name: mouse
  passThrough: true
  enterCommand: "notify-send 'mouse layer entered'"
  exitCommand: "notify-send 'mouse layer exited'"
  bindings:
    q: layer initial
    space: layer mouse
    r: reload-config

    h: move -1  0
    j: move  0  1
    k: move  0 -1
    l: move  1  0

    w: move  2  0
    b: move -2  0

    p: scroll up
    n: scroll down

    c: copy
    v: paste
    x: cut

    e: speed 0.2
    capslock: speed 2.0
    leftctrl: speed 2.0
    leftshift: speed 3.0
    leftalt: speed 4.0

    f: button left
    d: button middle
    s: button right

- name: arrows
  passThrough: false
  bindings:
    k: up
    h: left
    j: down
    l: right
    q: esc
    w: backspace
    r: delete
    v: enter
    _: rightalt+_

- name: system
  passThrough: true
  enterCommand: "notify-send 'system layer entered'"
  exitCommand: "notify-send 'system layer exited'"
  bindings:
    q: layer initial
    r: reload-config

    h: brightnessdown
    j: volumedown
    k: volumeup
    l: brightnessup

    m: mute
    n: nextsong
    p: previoussong
    space: playpause

    u: tap-hold u ; exec poweroff ; 1000
    i: tap-hold i ; exec reboot ; 1000
    o: tap-hold o ; sleep ; 1000
