devices:
# - "/dev/input/by-id/usb-SINO_WEALTH_Gaming_KB-event-kbd"
# - "/dev/input/by-id/usb-Logitech_Logi_TKL_Mechanical_Keyboard-event-kbd"

startCommand: "ms qwerty"

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 400.0
mouseAccelerationCurve: 1.0

startMouseSpeed: 0.0

mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: qwerty
  bindings:
    esc: multi esc ; exec ms qwerty
    capslock: tap-hold-next esc ; leftctrl ; 150

    # leftalt: tap-hold leftalt ; toggle-layer nav_right ; 150
    # rightalt: tap-hold rightalt ; toggle-layer nav_left ; 150

    f: tap-hold f ; toggle-layer nav_right ; 200
    # semicolon: tap-hold semicolon ; toggle-layer nav_left ; 200

- name: homerow
  passThrough: true
  bindings:
    esc: multi esc ; exec ms qwerty
    capslock: multi layer qwerty ; exec ms qwerty

    leftalt: tap-hold leftalt ; toggle-layer nav_right ; 150
    rightalt: tap-hold rightalt ; toggle-layer nav_left ; 150

    a: tap-hold a ; leftalt ; 150
    s: tap-hold s ; leftctrl ; 150
    d: tap-hold d ; leftshift ; 150
    f: tap-hold f ; leftmeta ; 150

    j: tap-hold j ; leftmeta ; 150
    k: tap-hold k ; leftshift ; 150
    l: tap-hold l ; leftctrl ; 150
    semicolon: tap-hold semicolon ; leftalt ; 150

    w: tap-hold w ; toggle-layer leftmeta_leftalt ; 150
    e: tap-hold e ; toggle-layer leftmeta_leftctrl ; 150

    i: tap-hold i ; toggle-layer leftmeta_leftctrl ; 150
    o: tap-hold o ; toggle-layer leftmeta_leftalt ; 150

- name: nav_left
  passThrough: true
  bindings:
    a: multi layer qwerty ; exec ms qwerty
    s: multi layer homerow ; exec ms homerow
    d: multi layer mouse ; exec ms mouse
    f: multi layer system ; exec ms system
    g: multi layer numpad ; exec ms numpad

- name: nav_right
  passThrough: true
  bindings:
    h: multi layer qwerty ; exec ms qwerty
    j: multi layer homerow ; exec ms homerow
    k: multi layer mouse ; exec ms mouse
    l: multi layer system ; exec ms system
    semicolon: multi layer numpad ; exec ms numpad

- name: leftmeta_leftctrl
  bindings:
    _: leftmeta+leftctrl+_

- name: leftmeta_leftalt
  bindings:
    _: leftmeta+leftalt+_

- name: mouse
  passThrough: true
  bindings:
    esc: multi esc ; exec ms qwerty
    capslock: multi layer qwerty ; exec ms qwerty

    leftalt: tap-hold leftalt ; toggle-layer nav_right ; 200
    rightalt: tap-hold rightalt ; toggle-layer nav_left ; 200

    u: move -1 -1
    i: move  1 -1

    n: move -1  1
    m: move  1  1

    l: move  1  0
    h: move -1  0
    j: move  0  1
    k: move  0 -1

    w: move  2  0
    b: move -2  0

    f: button left
    d: button middle
    s: button right

    leftshift: toggle-layer mouse_shift
    rightshift: toggle-layer mouse_shift

    y: multi leftctrl+c ; layer qwerty
    c: leftctrl+leftshift+c
    v: leftctrl+leftshift+v

- name: mouse_shift
  passThrough: false
  bindings:
    j: scroll down
    k: scroll up

    w: move  4  0
    b: move -4  0

    a: speed 0.1
    s: speed 0.5
    d: speed 4
    f: speed 8
    g: speed 10

- name: system
  passThrough: true
  bindings:
    esc: multi esc ; exec ms qwerty
    capslock: multi layer qwerty ; exec ms qwerty

    leftalt: tap-hold leftalt ; toggle-layer nav_right ; 200
    rightalt: tap-hold rightalt ; toggle-layer nav_left ; 200

    r: multi reload-config ; exec ms qwerty

    h: mute
    j: volumedown
    k: volumeup

    u: tap-hold u ; exec poweroff ; 1000
    i: tap-hold i ; exec reboot ; 1000
    o: tap-hold o ; sleep ; 1000

- name: numpad
  passThrough: true
  bindings:
    esc: multi esc ; exec ms qwerty
    capslock: multi layer qwerty ; exec ms qwerty

    leftalt: tap-hold leftalt ; toggle-layer nav_right ; 200
    rightalt: tap-hold rightalt ; toggle-layer nav_left ; 200

    q: k1
    w: k2
    e: k3
    r: k4
    t: k5
    y: k6
    u: k7
    i: k8
    o: k9
    p: k0
