# devices:
# - "/dev/input/by-id/usb-*-event-kbd"

# startCommand: ""

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 400.0
mouseAccelerationCurve: 1.0

startMouseSpeed: 0.0

mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: qwerty
  bindings:
    f13: layer mouse

- name: mouse
  passThrough: false
  bindings:
    esc: layer qwerty

    l: move  1  0
    h: move -1  0
    j: move  0  1
    k: move  0 -1

    w: move  2  0
    b: move -2  0

    f: button left
    d: button middle
    s: button right

    leftshift: toggle-layer mouse_shift
    rightshift: toggle-layer mouse_shift

    y: leftctrl+c
    p: leftctrl+p
    c: leftctrl+leftshift+c
    v: leftctrl+leftshift+v

- name: mouse_numpad
  passThrough: true
  bindings:

    u: move -1 -1
    i: move  0 -1
    o: move  1 -1

    j: move -1  0
    # k: button left
    l: move  1  0

    m: move -1  1
    comma: move  0  1
    dot: move  1  1

    w: move  2  0
    b: move -2  0

    f: button left
    d: button middle
    s: button right

    leftshift: toggle-layer mouse_shift
    rightshift: toggle-layer mouse_shift

    y: leftctrl+c
    p: leftctrl+p
    c: leftctrl+leftshift+c
    v: leftctrl+leftshift+v

- name: mouse_shift
  passThrough: false
  bindings:
    j: scroll down
    k: scroll up

    w: move  4  0
    b: move -4  0

    a: speed 0.1
    s: speed 0.5
    d: speed 4
    f: speed 8
    g: speed 10
