# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: deepseek
clients:

- type: openai-compatible
  name: deepseek
  api_base: https://api.deepseek.com

- type: openai-compatible
  name: r2
  api_base: http://r2v2:11434/v1
  models:
  - name: phi4:latest
  - name: codellama:latest
  - name: codestral:latest
  - name: mixtral:latest
